<?php


echo json_encode(
	[
	'code'=>400,
	'msg'=>'good',
	'data'=>array(
		0=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		1=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		2=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		3=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		4=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		5=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		6=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		),
		7=>array(
			'listcon'=>array(
				'name'=>'Camera',
				'date'=>'2015-05-12',
				'longitude'=>'192.32',
				'latitude'=>'123.12'
				),
			'iconurl'=>'images/file_download.png',
			'downloadurl'=>'#'
		)
	)
	]
);


?>